version: '3.8'

services:
  postgres_nlw:
    container_name: nlw_expert_notes_pg
    image: postgres:13.1-alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=notes_pg